### ISSUE TITLE
Move config to settings

### ISSUE THREAD

**Issue by ne-ray** [vojtasvoboda/oc-reservations-plugin#15]
https://github.com/Ne-Ray/oc-reservations-plugin/tree/feature/config_to_settings

**Comment by vojtasvoboda** [comment]
Hi Ilya, could you please send pull request with your changes? Thank you very much.

**Comment by ne-ray** [comment]
vojtasvoboda, I am working on new change (translate front-end).

**Comment by vojtasvoboda** [comment]
Thanks for your request, I need to test it. The thing is, that this changes has to be backward compatible - some people can already using this plugin and they are some values set in config file (for example time slot lenght) :-( We need to keep config values and use it in combination with Setting model.

**Comment by Ne-Ray** [comment]
Settings have a default value. default value = old value in config.

**Comment by Ne-Ray** [comment]
I change [format in this line](https://github.com/vojtasvoboda/oc-reservations-plugin/blob/master/config/config.php#L47), but not change [in here](https://github.com/vojtasvoboda/oc-reservations-plugin/blob/master/assets/js/reservationform.js#L10), I have Exeption Carbon.

**Comment by ne-ray** [comment]
Add backward compatible https://github.com/vojtasvoboda/oc-reservations-plugin/pull/18/commits/add121a57f5d75c14cf34624f5c7c99807c35c97

**Comment by vojtasvoboda** [comment]
Hi, I'll check the pull request today, but it is huge :-) It takes me maybe an hour to check it and test it.

**Comment by vojtasvoboda** [comment]
If those translations (language files, language template strings) could be separated to special pull request without anything other, that will be super great! And it will help me a lot because now it is a little bit hard to check it in one batch.

**Comment by ne-ray** [comment]
ok

**Comment by ne-ray** [comment]
https://github.com/vojtasvoboda/oc-reservations-plugin/pull/19 only translate (front, settings, and fix error)

**Comment by vojtasvoboda** [comment]
All tested and merged. Plugin update now ready at the Market as version 1.0.13.

Fixed by #19.
