### ISSUE TITLE
Day of week and work time

### ISSUE THREAD

**Issue by ne-ray** [vojtasvoboda/oc-reservations-plugin#17]
Add settings day of week and work time.
And fix get attributes from settings
[/assets/js/reservationform.js#L10](https://github.com/vojtasvoboda/oc-reservations-plugin/blob/master/assets/js/reservationform.js#L10)
[/assets/js/reservationform.js#L21](https://github.com/vojtasvoboda/oc-reservations-plugin/blob/master/assets/js/reservationform.js#L21)

**Comment by vojtasvoboda** [comment]
And also time format: https://github.com/vojtasvoboda/oc-reservations-plugin/blob/master/assets/js/reservationform.js#L20

**Comment by Ne-Ray** [comment]
And fix: if choose time 00:00 (interval = 15 minutes, lenght book = 2 hours) then blocked time 23:15, 23:30, 23:45 (at one day)

**Comment by Ne-Ray** [comment]
https://github.com/Ne-Ray/oc-reservations-plugin/tree/feature/issues%2317

**Comment by ne-ray** [comment]
Hi. It's code return all book dates [/components/ReservationForm.php#L110](https://github.com/vojtasvoboda/oc-reservations-plugin/blob/master/components/ReservationForm.php#L110)
I think return after current date

**Comment by ne-ray** [comment]
https://github.com/vojtasvoboda/oc-reservations-plugin/pull/20

**Comment by vojtasvoboda** [comment]
Fixed by #20
