### ISSUE TITLE
how the user get that his reservation is confirmed by admin

### ISSUE THREAD

**Issue by shajidkhn26** [vojtasvoboda/oc-reservations-plugin#2]
Hello i have used your plugin and it is very good but suppose a person reserved a date then how he will get confimation.

**Comment by vojtasvoboda** [comment]
There is nothing like "reservation confirmation email", but you can send pull request, or I can implement it in the future.

Thanks for hint :-)

**Comment by shajidkhn26** [comment]
So i will be waiting for this.Thank you

**Comment by vojtasvoboda** [comment]
Hi @shajidkhn26, just letting you know, that plugin now have both User confirmation and Admin confirmation by email. Check:

https://github.com/vojtasvoboda/oc-reservations-plugin/tree/master/views/mail
