### ISSUE TITLE
Count reservations in one time interval

### ISSUE THREAD

**Issue by ne-ray** [vojtasvoboda/oc-reservations-plugin#22]
example: I have 2 room for reservation, but now one time interval we have one reservation.
This issue conflict with your `Reservations Units plugin` (may be).
This case hard do (1 hour interval, 2 hours lenght, 2 count ):
1 reservation start 2017-05-15 10:00 (to 12:00)
2 reservation start 2017-05-15 11:00 (to 13:00)
We have empty 1 reservation from 2017-05-15 12:00 (to 13:00).

What do you think about this issue?

**Comment by vojtasvoboda** [comment]
You are right, this functionality is part of the [Reservations Units](https://octobercms.com/plugin/vojtasvoboda-reservationsunits) plugin. This plugin is just for one reservation at a time.

**Comment by ne-ray** [comment]
<s>This feature would be useful for some users. (book room, doctor, service). I will do it in my free time.</s> I will buy your plugin.

**Comment by vojtasvoboda** [comment]
Hold on! :-) Keep in mind, that with this new feature you made my Reservation Units useless :-) So probably I will not approve it.

I like the [freemium](https://en.wikipedia.org/wiki/Freemium) strategy where some part of work is for free and you will pay just for extensions. Working on October plugins takes a lot of time and the money comes from these extensions gives me more space for working on other plugins.

This is the reason why I made Reservation base plugin for free and now I'm working on other extensions (Units, Calendar, Reviews) and they will be paid.

**Comment by ne-ray** [comment]
@vojtasvoboda Sorry, I misread your phrase above.

**Comment by vojtasvoboda** [comment]
Thanks a lot. If you want some other coupons, please let me know, I will generate another. But the minimum amount is $5 which is minimum given by October Market (not from me).

30% of the price goes to the OctoberCMS as a donation.

**Comment by ne-ray** [comment]
@vojtasvoboda thx you too.
