### ISSUE TITLE
French for picker

### ISSUE THREAD

**Issue by m-paniez9292** [vojtasvoboda/oc-reservations-plugin#24]
Hi,

Great plugin.

To activate french translation in the picker (front), you need add in vojtasvoboda/reservations/components/ReservationForm.php (l 28) : 
`'fr' => 'fr_FR',`

Thanks

**Comment by vojtasvoboda** [comment]
Hi,

plugin version 1.1.2 with requested changes is now ready at the Market, or for the update from your backend.

Thanks for your idea
Vojta
