### ISSUE TITLE
Missing pickers

### ISSUE THREAD

**Issue by ghost** [vojtasvoboda/oc-reservations-plugin#25]
Hi!

It's necessary to install pickers manually?
![image](https://user-images.githubusercontent.com/6217617/30564332-95ac3e9c-9cbc-11e7-95e7-a99be6e4d138.png)

jQuery is loaded, and there are no errors.

**Comment by vojtasvoboda** [comment]
Hi, no it's not. Do you see this files loaded in HTML:

```
/plugins/vojtasvoboda/reservations/assets/vendor/pickadate/lib/compressed/themes/classic.css
/plugins/vojtasvoboda/reservations/assets/vendor/pickadate/lib/compressed/themes/classic.date.css
/plugins/vojtasvoboda/reservations/assets/vendor/pickadate/lib/compressed/themes/classic.time.css
/plugins/vojtasvoboda/reservations/assets/vendor/pickadate/lib/compressed/picker.js
/plugins/vojtasvoboda/reservations/assets/vendor/pickadate/lib/compressed/picker.date.js
/plugins/vojtasvoboda/reservations/assets/vendor/pickadate/lib/compressed/picker.time.js
```

?

**Comment by ghost** [comment]
@vojtasvoboda Hello!

there are no css files

**Comment by vojtasvoboda** [comment]
Hi @dunets. I just created clean October installation with Reservations plugin and it works fine:

![snimek obrazovky 2017-09-22 v 21 36 34](https://user-images.githubusercontent.com/374917/30761359-3adcea64-9fde-11e7-9dc8-503d6d80d143.png)

Can you upload your project somewhere public, or private and send me a link? Seems to be a problem with your theme maybe?
