### ISSUE TITLE
Exclude dates

### ISSUE THREAD

**Issue by markandmedia** [vojtasvoboda/oc-reservations-plugin#26]
Is it possible to exclude certain days without having to create a reservation for every available interval-slot on that specific date? Maybe something with a custom length? In that case I can exclude for example Christmas and holidays?

**Comment by vojtasvoboda** [comment]
This is not possible by default, but you can use plugin's event `vojtasvoboda.reservations.processReservation` and use it for extending the logic.

The Christmas thing could be solved something like that (not tested). In your own Plugin.php put that snippet:

```
public function boot()
{
    Event::listen('vojtasvoboda.reservations.processReservation', function (&$data) {
        // we already has date as Carbon instance
        $date = $data['date'];
        if ($date >= '2017-12-23' || $date <= '2017-12-31') {
            throw new ApplicationException('Sorry, but we are closed at holidays.');
        }
    });
}
```
