### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by geoffropedromancini** [vojtasvoboda/oc-reservations-plugin#27]
Hi,

I have just added this plugin to my project and its not working. Its not showing in my backend menu, nor in my updates and plugins list of plugins however it has installed. If i go to the the plugins menu i can VojtaSvoboda.TwigExtensions but that's it. If i go to the actual pluging directory i can see vojtasvoboda reservationscalendar. From the backend if i click Reservations -> reservationscalendar I get an error "Unable to find the specified settings."

Whats going on here?

**Comment by vojtasvoboda** [comment]
Hi, are you talking about Reservations plugin? Because in your text are mentioned three plugins (Reservations, Reservations Calendar and Twig Extensions) :-)

One thing you can do now - try to log out from Backend section and log in again.
