### ISSUE TITLE
Method [validateReservation] does not exist

### ISSUE THREAD

**Issue by docu30** [vojtasvoboda/oc-reservations-plugin#28]
Hello!
When I try to make a reservation either from the frontend or from the backend I get this error:
Method [validateReservation] does not exist. "On line 1140 of /Applications/MAMP/htdocs/october/vendor/laravel/framework/src/Illuminate/Validation/Validator.php
Can you help me with this?
Thanks!

**Comment by vojtasvoboda** [comment]
Hello, which version of OctoberCMS and which version of PHP are you using?

**Comment by docu30** [comment]
I'm using the latest version of OctoberCms (just downloaded from official site), PHP Version 7.2.10.

**Comment by vojtasvoboda** [comment]
I have tried the same with:

`PHP 7.2.12 (cli) (built: Nov 24 2018 18:24:34) ( NTS )`

<img width="986" alt="snimek obrazovky 2018-12-12 v 11 02 35" src="https://user-images.githubusercontent.com/374917/49862122-be88f500-fdfd-11e8-9f9f-326168119498.png">
<img width="1141" alt="snimek obrazovky 2018-12-12 v 11 04 04" src="https://user-images.githubusercontent.com/374917/49862127-c183e580-fdfd-11e8-9ba1-97400ac8cdb5.png">
<img width="1169" alt="snimek obrazovky 2018-12-12 v 11 08 38" src="https://user-images.githubusercontent.com/374917/49862361-52f35780-fdfe-11e8-947f-03e9f22bdce1.png">
<img width="1246" alt="snimek obrazovky 2018-12-12 v 11 08 51" src="https://user-images.githubusercontent.com/374917/49862363-54bd1b00-fdfe-11e8-8185-983ccc7d9956.png">

Everything works as expected.

Could you please try to insert `public $elevated = true;` at the beginning of the plugins/vojtasvoboda/reservations/Plugins.php file please, if helps?

<img width="921" alt="snimek obrazovky 2018-12-12 v 11 10 04" src="https://user-images.githubusercontent.com/374917/49862509-9c43a700-fdfe-11e8-9c13-127c2617e2bf.png">

**Comment by docu30** [comment]
Unfortunately the same error.
Looks like there's something wrong with my computer. I installed the plugin on windows 10 and it works perfectly. On mac osx mojave appears those errors. 
I think maybe I have to activate something in php.ini. I'm still trying to make it work. Thank you for your support.

**Comment by vojtasvoboda** [comment]
I have also Mac with Mojave (10.14.2) and it works. If you are using MAMP, try to run your website with PHP development server:
- open Terminal
- go to the folder with your website
- run `php artisan serve` or `php -S localhost:8080` (or different port, when it fails)

Maybe you got different PHP configurations and it will works.
