### ISSUE TITLE
Enhance form with cart ?

### ISSUE THREAD

**Issue by Incremental92** [vojtasvoboda/oc-reservations-plugin#36]
Hello, I'd like to enhance your great plugin to add a kind of cart to be collected in a regular shop.
I can use your calendar to limit the collects per time slot, but how could I insert a cart system or a form for ordering ?
Were should I modify the code for this ?
Thanks

**Comment by vojtasvoboda** [comment]
Hello @Incremental92, what is the main goal? To be able to make more reservations at the one time? Or to integrate Reservations plugin with existing E-shop solution?

**Comment by Incremental92** [comment]
Hello Vojta, there are 2 goals :
1) check if a time slot of 1 hour could accept more commands to be collected
2) if yes being able to reserve goods with a simple order form or very simple cart.
Just to order before going to the shop for payment and avoid 'collisions' at the cashier.
ie : instead of the message field, I'd like to insert a simple cart...

Thanks for help

**Comment by vojtasvoboda** [comment]
Sorry @Incremental92, there is no functionality like simple cart, this is only a simple reservation form. It checks only one time slot (with preconfigured duration, for example 15 minutes).

**Comment by Incremental92** [comment]
Dobry den Vojta,
is it allowed to modify your plugin for my specific usage ?
and could you give me some tricks for that ?  ie where to find the
validation function ?
Thanks

**Comment by vojtasvoboda** [comment]
@Incremental92 There are two ways how to change plugin's behavior:

A) You can change validation rules in this file: https://github.com/vojtasvoboda/oc-reservations-plugin/blob/master/models/Reservation.php#L28 But it will be overwritten with the first update, so it's better to not updating CMS :-)

B) Clean way - see documentation https://octobercms.com/docs/plugin/extending

Good luck

**Comment by Incremental92** [comment]
ok thanks a lot
