### ISSUE TITLE
Approval

### ISSUE THREAD

**Issue by maishedu** [vojtasvoboda/oc-reservations-plugin#41]
Is there a way to send mail on approval

**Comment by vojtasvoboda** [comment]
Hi @maishedu, this feature is on TODO list and waiting for implementation. Feel free to send pull request.

**Comment by maishedu** [comment]
Thanks, If you could provide a date you plan to implement this or guide me on where to start implementing this so that I can do it myself. In the controllers, I couldn't find a status change. Plan to do when the status changes to approval send mail. I would really appreciate your help. Thank you.

**Comment by vojtasvoboda** [comment]
I don't have any estimation, so I would recommend you to start implementing.

You have to add the new section to [Settings](https://github.com/vojtasvoboda/oc-reservations-plugin/blob/master/models/settings/fields.yaml) to have a chance to "Turn on" approval mails. Then extend locale files with new translations.

Then create new [mailer](https://github.com/vojtasvoboda/oc-reservations-plugin/tree/master/mailers) for creating approval mail, create template.

On the end add "afterSave" hook to Reservation model class to send the mail. But only if enabled in settings.

**Comment by maishedu** [comment]
Thanks. One more clarification. Kindly explain further the line "On the end add "afterSave" hook to Reservation model class to send the mail. But only if enabled in settings.". Thank you again

**Comment by vojtasvoboda** [comment]
Here you have documentation regarding `afterSave` event: https://octobercms.com/docs/database/model#events

And the logic "only if enabled in setting" you can take from [AdminMailer](https://github.com/vojtasvoboda/oc-reservations-plugin/blob/master/mailers/ReservationAdminMailer.php) which is sent only if enabled in settings.

**Comment by maishedu** [comment]
Thanks Very helpful
