### ISSUE TITLE
Can not install on PostgreSQL

### ISSUE THREAD

**Issue by maraerben** [vojtasvoboda/oc-reservations-plugin#43]
Hello,

I wanted to use your plugin in my OC project, but I had an issue during installation.

<img width="618" alt="Snímek obrazovky 2022-02-08 v 11 11 34" src="https://user-images.githubusercontent.com/17090177/152966110-75237f45-b57d-4dd1-96a1-6ff774b30ab6.png">

I think it corresponds with this line of code: https://github.com/vojtasvoboda/oc-reservations-plugin/blob/master/updates/create_statuses_table.php#L20

Some RDBMSs maybe represents boolean as number so this migration works with them, but it does not work with Postgres.

I suggest to change data type of the `sort_order` column to `integer`.

**Comment by vojtasvoboda** [comment]
Fixed in #44, could you please review the changes? Thanks

**Comment by maraerben** [comment]
That was quick! Yes, you MR works great in my local environment.

**Comment by vojtasvoboda** [comment]
New version 1.1.10 is ready, so you can run update ;-)

If you were happy with the support, please consider [a small donation (button Donate)](https://octobercms.com/plugin/vojtasvoboda-reservations), since it is a free plugin :-)
