### ISSUE TITLE
Change default routes?

### ISSUE THREAD

**Issue by bojko91** [vojtasvoboda/oc-reservations-plugin#49]
Helo,
Could you tell me how can i change default routes? 
admin/vojtasvoboda/reservations/reservations -> i want to make it admin/vojtasvoboda/reservations/rv, but didnt find where

**Comment by vojtasvoboda** [comment]
Routes are created automatically based on [controller](https://github.com/vojtasvoboda/oc-reservations-plugin/blob/master/controllers/Reservations.php) name.

One way could be to rename this controller and all routes in the whole plugin. But I would suggest to define Rewrite in .htaccess like that:

```
RewriteRule ^admin/vojtasvoboda/reservations/reservations$ admin/vojtasvoboda/reservations/rv [L,QSA]
```

See more at [manual](https://httpd.apache.org/docs/2.4/mod/mod_rewrite.html).
